'use strict';

const { round, inr } = require('../utils/math');
const { pctText } = require('./scoring');

/**
 * Deterministic explanations. Every sentence is assembled from numbers the
 * engine computed - nothing here is generated by a language model, so the
 * "why" attached to a decision is always reproducible from the stored inputs.
 */

function explainBuy({ symbol, entry, score, f, regime, params, sector, sizing, rank, universeSize, kind, trigger }) {
  const risk = entry.risk;
  const topComponents = Object.entries(score.components)
    .sort((a, b) => b[1].contribution - a[1].contribution)
    .slice(0, 3)
    .map(([k, v]) => `${k.replace(/([A-Z])/g, ' $1').toLowerCase()} ${v.score}`);
  const whyBuy =
    kind === 'ADD'
      ? `${symbol} is already held, its thesis is intact and it is below its target weight, so part of the new capital tops it up.`
      : `${symbol} ranks #${rank} of ${universeSize} in the universe with a composite momentum score of ${score.total}/100 (strongest components: ${topComponents.join(', ')}). ${
          trigger === 'REPLACEMENT' ? 'It replaces a weaker holding. ' : ''
        }Trend, momentum and relative strength all pass the entry rules.`;
  const whyNow = `${entry.headline}. ${entry.setup !== 'NONE' ? `Setup: ${entry.setup.toLowerCase()}. ` : ''}Market regime is ${regime.regime} (score ${regime.score}/100), which permits new purchases${
    regime.policy.scoreBonus ? ` with a ${regime.policy.scoreBonus}-point score premium` : ''
  }.`;
  const whyThisStock = [
    `3M return ${pctText(f.ret.m3)}, 6M ${pctText(f.ret.m6)}; ${pctText(f.rs.vsIndex3m)} vs NIFTY over 3M`,
    f.trend.stack ? `${params.emaPeriods.join('/')} EMAs fully stacked` : `${f.trend.stackCount}/3 EMA pairs aligned`,
    `ADX ${round(f.tech.adx, 0)}, RSI ${round(f.tech.rsi, 0)}, volume ${round(f.flow.rel, 2)}x average`,
    sector && Number.isFinite(sector.ret3m) ? `sector ${pctText(sector.ret3m)} over 3M` : null,
  ]
    .filter(Boolean)
    .join('; ');
  const whyThisPrice = `Reference price ${inr(f.price, 2)} is ${round(Math.abs(f.tech.extensionAtr), 1)} ATR ${f.tech.extensionAtr >= 0 ? 'above' : 'below'} the ${params.emaPeriods[0]}-EMA (extension limit ${params.maxExtensionAtr} ATR) and ${pctText(f.tech.pctFromHigh52)} from the 52-week high; stop ${inr(risk.stop, 2)} (${risk.stopType}) gives a reward/risk of ${risk.rewardRisk} to ${inr(risk.target, 2)} (${risk.targetType}).`;
  const howMuch = `${inr(sizing.value)} (${round((sizing.value / sizing.equity) * 100, 1)}% of portfolio) - ${sizing.basis}. Risk if the stop is hit: ${inr(sizing.riskAmount)} (${round((sizing.riskAmount / sizing.equity) * 100, 2)}% of portfolio).`;
  const howManyShares = `${sizing.qty} share${sizing.qty === 1 ? '' : 's'} at about ${inr(f.price, 2)}${sizing.clipNotes.length ? ` (${sizing.clipNotes.join('; ')})` : ''}.`;
  return {
    whyBuy,
    whyNow,
    whyThisStock,
    whyThisPrice,
    howMuch,
    howManyShares,
    confirms: entry.confirmations,
    invalidates: entry.invalidation,
    expectedHolding: `${entry.expectedHolding}. Holding period is not an exit rule: the position is kept while the thesis stays valid.`,
    risk: `Stop ${inr(risk.stop, 2)} (${round(risk.riskPct * 100, 1)}% below entry). Position risk ${inr(sizing.riskAmount)}. Momentum stocks can gap through stops on news.`,
  };
}

function explainSell(action, exit, position, f) {
  return {
    whySell: exit.reasons.join(' '),
    headline: exit.headline,
    result: `${pctText(exit.gainPct)} on cost ${inr(position.avgPrice, 2)} (${exit.rMultiple}R).`,
    thesis: exit.thesis.map((t) => `${t.ok ? 'OK' : 'FAILED'} - ${t.label}: ${t.detail}`),
    nextStep:
      action === 'REDUCE'
        ? 'Remaining shares stay on the ratcheting stop; the next review decides whether to exit them.'
        : 'Proceeds return to cash and become available for the highest-ranked qualifying stock.',
    price: f ? f.price : null,
  };
}

function explainHold(exit, position) {
  return {
    whyHold: exit.reasons.join(' '),
    headline: exit.headline,
    thesis: exit.thesis.map((t) => `${t.ok ? 'OK' : 'FAILED'} - ${t.label}: ${t.detail}`),
    warnings: exit.warnings,
    result: `${pctText(exit.gainPct)} on cost ${inr(position.avgPrice, 2)} (${exit.rMultiple}R, peak ${exit.peakR}R). Protective stop ${inr(exit.stopPrice, 2)} (${exit.stopType.toLowerCase().replace(/_/g, ' ')}).`,
  };
}

function explainWait(symbol, entry, score, extra) {
  return {
    headline: entry ? entry.headline : `WAIT - ${extra || 'not eligible'}`,
    waitFor: entry ? entry.waitFor : [],
    note: extra || null,
    score: score ? score.total : null,
  };
}

function summarizeRun({ asOf, equity, cash, invested, positionsCount, regime, size, decisions, allocation, triggers, capitalEvent, review, drawdown, deployable }) {
  const buys = decisions.filter((d) => d.action === 'BUY');
  const sells = decisions.filter((d) => ['SELL', 'EXIT'].includes(d.action));
  const reduces = decisions.filter((d) => d.action === 'REDUCE');
  const holds = decisions.filter((d) => d.action === 'HOLD');
  const waits = decisions.filter((d) => d.action === 'WAIT');
  const lines = [];
  lines.push(`As of the ${asOf} close: portfolio value ${inr(equity)} (cash ${inr(cash)}, invested ${inr(invested)} in ${positionsCount} stock${positionsCount === 1 ? '' : 's'}).`);
  lines.push(`Market regime: ${regime.regime} (score ${regime.score}/100). ${regime.reasons.slice(0, 2).join(' ')}`);
  lines.push(size.explanation);
  if (triggers.length) lines.push(`Triggers: ${triggers.map((t) => t.detail).join('; ')}.`);
  if (drawdown && drawdown.halted) lines.push(`Drawdown halt active (${round(drawdown.drawdown * 100, 1)}% below peak): no new purchases.`);
  if (allocation && (capitalEvent || buys.length)) lines.push(allocation.explanation);
  let answer;
  if (sells.length) answer = 'SELL';
  else if (buys.length) answer = 'BUY';
  else if (reduces.length) answer = 'REDUCE';
  else if (holds.length) answer = 'HOLD';
  else answer = 'WAIT';
  const parts = [];
  if (sells.length) parts.push(`sell/exit ${sells.map((d) => d.symbol).join(', ')}`);
  if (reduces.length) parts.push(`reduce ${reduces.map((d) => d.symbol).join(', ')}`);
  if (buys.length) parts.push(`buy ${buys.map((d) => `${d.symbol} x${d.quantity}`).join(', ')}`);
  if (holds.length) parts.push(`hold ${holds.length} position${holds.length === 1 ? '' : 's'}`);
  const headline = parts.length ? `Action: ${parts.join('; ')}.` : `No action today - ${waits.length ? `${waits.length} candidate${waits.length === 1 ? '' : 's'} on the watch list, none has a confirmed entry.` : 'nothing qualifies.'}`;
  lines.push(headline);
  if (!buys.length && waits.length) {
    const first = waits.find((w) => w.waitFor && w.waitFor.length);
    if (first) lines.push(`Best candidate ${first.symbol} (score ${first.score}): ${first.reason}. Waiting for: ${first.waitFor[0]}.`);
  }
  if (!review && !sells.length && !reduces.length) lines.push('This is not a review day; positions are only changed by protective stops or hard exit signals.');
  return {
    answer,
    headline,
    lines,
    text: lines.join('\n'),
    counts: { buy: buys.length, sell: sells.length, reduce: reduces.length, hold: holds.length, wait: waits.length },
    deployable: round(deployable, 2),
  };
}

module.exports = { explainBuy, explainSell, explainHold, explainWait, summarizeRun };
