/**
 * Build-time entry for the Charts Protect SMC + ATM bundle.
 * Runtime code requires ./bundle.js (generated by build.js).
 */
export { analyzeSmc } from '../../../palagai/src/app/core/charts/smc/smc-analyze';
export { SmcAlertTracker } from '../../../palagai/src/app/core/charts/smc/smc-alerts';
export { buildAtmOrderPlan, atmOrderFields } from '../../../palagai/src/app/core/orders/atm-order.util';
export { resolveCrudeOilMiniFuturesToken } from '../../../palagai/src/app/core/utils/instrument-resolver.util';
export { lotsFromAvailableFunds, RS_PER_LOT } from '../../../palagai/src/app/core/paper-desk/lots-from-funds';
